run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam

linters-settings:
  goimports:
    local-prefixes: github.com/mescon/muximux3

issues:
  exclude-rules:
    # Ignore error checking for response writes (common pattern)
    - linters:
        - errcheck
      source: "json\\.NewEncoder.*\\.Encode"
    - linters:
        - errcheck
      source: "w\\.Write"
