version: "2"
run:
  tests: true
linters:
  enable:
    - misspell
    - unconvert
    - unparam
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
        source: json\.NewEncoder.*\.Encode
      - linters:
          - errcheck
        source: w\.Write
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/mescon/muximux3
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
