version: "2"
run:
  tests: true
linters:
  enable:
    - bodyclose
    - durationcheck
    - errname
    - gocritic
    - gosec
    - misspell
    - nilerr
    - unconvert
    - unparam
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
        source: json\.NewEncoder.*\.Encode
      - linters:
          - errcheck
        source: w\.Write
    paths:
      - third_party$
      - builtin$
      - examples$
linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
  gosec:
    excludes:
      - G104  # unhandled errors on deferred Close()
      - G304  # file path from variable (validated)
      - G402  # TLS InsecureSkipVerify (user-configurable per app)
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/mescon/muximux/v3
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
