sonar.projectKey=mescon_Muximux
sonar.organization=mescon
sonar.projectVersion=3.0.15

sonar.sources=.
sonar.exclusions=**/node_modules/**,**/dist/**,**/vendor/**,**/*_test.go,**/*.test.ts,**/*.spec.ts,**/testdata/**,**/dev/**,**/paraglide/**

sonar.tests=.
sonar.test.inclusions=**/*_test.go,**/*.test.ts,**/*.spec.ts

sonar.coverage.exclusions=cmd/**,**/*.svelte,web/public/sw.js
sonar.go.coverage.reportPaths=coverage.txt
sonar.javascript.lcov.reportPaths=web/coverage/lcov.info

sonar.sourceEncoding=UTF-8
